### ISSUE TITLE
Layer information doesn't display when using slic3r gcode even with enhancement 8 settings

### ISSUE THREAD

**Issue by chris-schmitz** [OllisGit/OctoPrint-DisplayLayerProgress#36]
Hi, 

I installed your plugin the other day. I use slic3r so I read up on [enhancement #8](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/8) to figure out how I need to adjust my gcode settings. 

From reading the discussion thread it seemed like all I needed to do was add the following text to my slic3r "before layer change g-code" section:

    ;LAYER:[layer_num]

I did that for a gcode I ran last night, but the layer information still didn't display. 

I'm using the prusa flavor of slic3r so I have other information in that section of the settings and I'm wondering if it's causing an issue. Here's a screen shot of my print settings in slic3r:

<img width="1436" alt="screen shot 2018-04-25 at 7 19 58 am" src="https://user-images.githubusercontent.com/2437424/39245377-32dd4f74-4859-11e8-8bed-231e91b0d350.png">

Am I adding the text wrong? Thanks for the help and the cool plugin :)

I'm using:

- Slic3r Prusa Edition version 1.38.7-prusa3d
- Prusa i3 MK3 printer
- OctoPrint 1.3.8 running on OctoPi 0.14.0

**Comment by OllisGit** [comment]
Is it possible to provide your gcode, so that I can analyse the commands?

**Comment by chris-schmitz** [comment]
Sure thing. 

[rook.gcode.zip](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/1947245/rook.gcode.zip)

**Comment by OllisGit** [comment]
I added your gcode to my development infrastucture (only virtual, no real printer on my windows-system) and everthings looks fine.

Is the layerinformation shown in navbar or is it a genaral issue? 

![image](https://user-images.githubusercontent.com/24205767/39249942-1e6ec576-48a0-11e8-885e-30922289e160.png)

**Comment by chris-schmitz** [comment]
It was the layer information in the side bar. In your screen shot where it says `Layer: - / 200` mine just says `Layer: - / -`.

I'm at work so I can't double check my settings, but once I get home I'll try it again and let you know. 

Thanks for taking a look at this so quickly.

**Comment by guardiande** [comment]
Just to let you know: Same here. Prusa MK2, Prusa slic3r 1.38.7.

**Comment by thebarto360** [comment]
Ami happens to me similar, I see layer 10 of - 0.0
it does not give me the total layers or the total height of z.

I checked the files as you say and I see the information you mention

**Comment by OllisGit** [comment]
I can't help without g-code!

**Comment by thebarto360** [comment]
[bamarillo.zip](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/1956586/bamarillo.zip)
sorry

**Comment by OllisGit** [comment]
Thx, now I can see the problem!
Orig. G-Code you provided:
```
...
; layer 1, Z=0.200
;LAYER:[layer_num]
T0
...
```
There are both layer-pattern included Simplify3D AND CURA (without a number)
The plugin layer-preprocessor transforms the G-Code into this:
```
...
M117 INDICATOR-Layer1
M117 INDICATOR-Layer
T0
...
```
So, you need to check your slicer settings to provide only one correctly filled pattern and I will optimize my plugin as well.

BR
Olli

**Comment by chris-schmitz** [comment]
I had a chance to test the rook gcode and I still don't get the layer progress readout in octoprint. I'm not sure how to try to narrow down the issue from here. Let me know if there's anything you think I should try. I'll be printing though out the weekend so if you have any suggestions I'll definitely give them a try.

**Comment by OllisGit** [comment]
@thebarto360 Did you try the new Version 1.4.1? 
With this version the second invalid cura-like comment will be ignored and it should work now.

By the way, I don't use  s3d, so it is better to provide screenshots with english-language.

BR
Olli

**Comment by guardiande** [comment]
This is what slic3r produces:

```
M204 S1000
;BEFORE_LAYER_CHANGE
;2.2


G1 F5760
G1 X217.924 Y23.215 E-0.76000
G1 E-0.04000 F2100.00000
G1 Z2.600 F7200.000
;AFTER_LAYER_CHANGE
;2.2
```

This is configured in slic3r's printer settings under `Custom G-Code`:

![image](https://user-images.githubusercontent.com/4947715/39405492-346b6d44-4ba6-11e8-89ba-e8389e3c04ee.png)

Will change that setting to include the format that your plugin needs and try again.

Sorry for bothering you as I should have RTFM.

But since OctoPrint already knows the current layer or at least the G-Code viewer does, wouldn't it be possible to hook onto that?

**Comment by OllisGit** [comment]
@guardiande Well, the g-code viewer do a lot of "magic" to calculate the values.

- The g-code parser works only in the browser, no apis/interfaces available to grep the information
- The octoprint has no access to layer-information see https://github.com/foosel/OctoPrint-DisplayZ/issues/2
- With layer-comments your are more flexible (I think)

BR 
Olli

**Comment by thebarto360** [comment]
@OllisGit Hi, I'm still having the same problem, I always use your latest version

regards
![1](https://user-images.githubusercontent.com/34549565/39599723-e269093c-4f1c-11e8-9625-bad82c5ec075.JPG)
![2](https://user-images.githubusercontent.com/34549565/39599724-e28603de-4f1c-11e8-83f2-ad82ed9781ba.JPG)
![3](https://user-images.githubusercontent.com/34549565/39599827-375c98dc-4f1d-11e8-8914-c6985ebaaba5.JPG)


[code.zip](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/1972476/code.zip)

**Comment by OllisGit** [comment]
@thebarto360 Thanks for the gcode. 
Now I could found an issue in the plugin. The line-parser didn't ignore comment-lines (starting with ;)  and in your code there is a lot of comented z-movement. The plugin crashed and could not evaluate the height nor the the layer information.

I improved the regular-expression, added error-handling and also added a busy-indicator, because files bigger than 10MB could take some time to evaluate the height/layer-info.

The new relase 1.5.1 is out, so please so kind at test it.

BR
Olli

**Comment by thebarto360** [comment]
@OllisGit hello, thank you very much for the new update, now if you show me the total number of layers and the height of z, although as I show in the wrong photos since it should be z = 4 and not z = 10 as sample, I will have I find the reason for the error.

again thanks for the inconvenience taken
regards
![1](https://user-images.githubusercontent.com/34549565/39647629-045ab7f2-4fe0-11e8-8afb-6b2b779aa7f4.JPG)
![2](https://user-images.githubusercontent.com/34549565/39647632-05b042fc-4fe0-11e8-9997-70e484f59691.JPG)

**Comment by OllisGit** [comment]
Please check also the selected "Total Height"-Methode in the plugin settings!

**Comment by thebarto360** [comment]
@OllisGit hello again, after entering settings and changing the total method, it shows me the correct height of z. You made me happy the day, thanks for your work

regards

**Comment by OllisGit** [comment]
@thebarto360 Your welcome! 

Yeah, now I can close this long running issue.
I you have further questions/issues, please feel free to create a new issue.

BR
Olli

**Comment by AbuMaia** [comment]
Hi Olli, just a comment, not an issue or question.

I'm running Slic3r 1.41.0-beta, and it appears that they don't like layer change commands that start with a semicolon anymore. The ;LAYER:[layer_num] just gives a blank space now.

Since I see that your plugin reads that in order to add M117 INDICATOR-LayerN to the gcode, I decided to save it a step and put that in the layer change gcode myself. M117 INDICATOR-Layer[layer_num] works well now.

Just an FYI so you would know, and maybe could add the info to the readme.

**Comment by tcurdt** [comment]
@AbuMaia why `M117 INDICATOR-Layer[layer_num]` shouldn't that be `M117 INDICATOR-Layer[layer_z]` instead?

**Comment by tcurdt** [comment]
Ah - nevermind. `[layer_z]` is in `mm` and `layer_num` is the current layer.

**Comment by OllisGit** [comment]
Or use this:
`count [;BEFORE_LAYER_CHANGE] Slic3r`
Thx, @crami for the hint: https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/75

http://projects.ttlexceeded.com/3dprinting_slic3r_gcode.html#other-custom-g-code

**Comment by ManuGithubSteam** [comment]
Hi

Sorry to did this up, but the problem is still there or reappearing in PrusaSlicer 2.1.

;BEFORE_LAYER_CHANGE in in the gcode also the the other lines mentioned in this and in #8

The plugin does not work. I see no top height and no current layers or the total layers.

I tried all the pre things with cura like in #8 but it did not work so i tried only one line ;Before Layer change but that also does not work.

This is in the Gcode, but it does not get read by the plugin.

;BEFORE_LAYER_CHANGE
G92 E0.0
;0.25
;LAYER:0

[CameraLamp v7_56m_Real PETG - 0.35mm QUALITY - MK3S - Volcano 0.4.zip](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/3694251/CameraLamp.v7_56m_Real.PETG.-.0.35mm.QUALITY.-.MK3S.-.Volcano.0.4.zip)

![Screenshot_20191006_124350](https://user-images.githubusercontent.com/3456994/66267880-15513680-e837-11e9-999c-da5e284f7c60.png)
![Screenshot_20191006_124423](https://user-images.githubusercontent.com/3456994/66267881-15513680-e837-11e9-8e97-f1b4f1860747.png)

Please help with fixing this :-)
Thanks

**Comment by OllisGit** [comment]
@ManuGithubSteam 
hmmm...it's working in my environment. 
![image](https://user-images.githubusercontent.com/24205767/66275713-a81bc080-e88b-11e9-81f8-ca21fd7c0d3f.png)

I reseted my plugin-settings, upload your gcode and after selecting your model the layer/height informations were shown.
It is important after changing the layer-expressions you need to re-upload your code, because the layer-analyse is only done during upload and not after selecting. 

BUT your gcode include "muliple-layer-indicators": 
- `;BEFORE_LAYER_CHANGE` appears 303 times
and
- `;LAYER:301` last layer entry

You should only use one! Remove `;BEFORE_LAYER_CHANGE` then the count - expression is not used, only the cura-style is used.

Please try again.

**Comment by ManuGithubSteam** [comment]
Hello @OllisGit 
Thanks for taking the time!

It works now sort of. The layer count is not correct.
See the picture:
![Screenshot_20191007_214645](https://user-images.githubusercontent.com/3456994/66343606-48391e80-e94c-11e9-8352-232345d4d753.png)

I did reupload the gcode and it works but the layers are not correct.
Here are my settings at the moment:

1		[;\s*LAYER:\s*([0-9]+).*]		CURA
1		[; layer ([0-9]+),.*]		Simplify3D
1		[;LAYER:([0-9]+).*]		ideaMaker
count	[; BEGIN_LAYER_OBJECT.*]		KISSlicer
count	[;BEFORE_LAYER_CHANGE]		Slic3r

In Prusasslicer i removed the ;LAYER: line. I prefer to stay stock and not add too much stuff to the gcode.

So it has to use: count	[;BEFORE_LAYER_CHANGE]		Slic3r
 i guess.

**Comment by OllisGit** [comment]
Hi @ManuGithubSteam ,

with incorrect layer count, you mean the difference between sidebar ("DisplayLayerProgress-Plugin") and Tab-Content ("Dashboard-Plugin"), right? 

You are already raised an issue about this topic: https://github.com/StefanCohen/OctoPrint-Dashboard/issues/81

From my point of view the issue is solved, because it is related to the dashboard plugin.

**Comment by michaelsheridan23** [comment]
I cannot get my MK3s setup to show the current layer. Can someone post a screen shot of their "Custom G-Code" screen is PrusaSlicer? I have tried what is suggested here and I am still getting a "Layer: - / 62" in my files. Obviously the 62 changes, that is just what I see on my current file.

**Comment by AbuMaia** [comment]
Michael: 
I have
M117 INDICATOR-Layer[layer_num]
in my "Before layer change g-code" section.

**Comment by h4nc** [comment]
@OllisGit everything works fine but the current layer number. I added 

;BEFORE_LAYER_CHANGE
;[layer_z]

to my "Before layer change g-code" section, but this only provided the total number. So what I get during printing is for example "-/50". Works fine for Cura prints. What am I doing wrong?

**Comment by OllisGit** [comment]
Hi @h4nc,
do you use the default layer indicator expressions?
If true you only need to add ```;BEFORE_LAYER_CHANGE``` to your g-code section.
After that, DLP just count the occurrence. 

Please attach your gcode  (as Zip) that was created by your slicer and also the g-code after uploading to OP (download from files-listing).

**Comment by OllisGit** [comment]
Hi @michaelsheridan23 , @AbuMaia , @h4nc !!!

This is a closed issue, next time please create a new issue. 
Because I am not observing closed issues, so I CAN''T HELP YOU!!

**Comment by h4nc** [comment]
> do you use the default layer indicator expressions?

@OllisGit I don't understand or I don't know if I use it. How can I tell. 

> Please attach your gcode (as Zip) that was created by your slicer and also the g-code after uploading to OP (download from files-listing).

Will do if your suggestions did not work

**Comment by OllisGit** [comment]
Hi @h4nc ,
the plugin scans the gcode (druing upload) for layer-indicators (cura use ```;LAYER:21```). This is done via regular expressions.
Because you didn't know about that, so you use the default settings!

![image](https://user-images.githubusercontent.com/24205767/74081229-f533bd00-4a4c-11ea-9e02-e3161b459da3.png)

**Comment by h4nc** [comment]
Ok, so I will delete 

;[layer_z]

from my slicer settings and try again.

**Comment by h4nc** [comment]
@OllisGit thanks now it working. Not a big issue, because it's good enough like that for me, but slic3r files have an offset of 1 layer. So when it's on layer 1 it shows me 2. 

In the Setting layer offset I have the standard value "1". So that makes sense.
I use cura and slic3r files. 

> Some slicers start at layer zero (like CURA) and some starts at layer one.
> Here you can add an offset to the layer count.

So this basically means that I have to decide for one to be shown correctly, right?

**Comment by OllisGit** [comment]
Yes!
